// <auto-generated />
using System;
using CarExpenses.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarExpenses.DAL.Migrations
{
    [DbContext(typeof(CarExpesesDbContext))]
    partial class CarExpesesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarExpenses.Model.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentMilage")
                        .HasColumnType("int");

                    b.Property<double>("EngineVolume")
                        .HasColumnType("float");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            CurrentMilage = 68500,
                            EngineVolume = 1.8,
                            FuelType = 3,
                            Model = "Corolla",
                            PurchaseDate = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 19850m,
                            UserId = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            CurrentMilage = 112300,
                            EngineVolume = 2.0,
                            FuelType = 1,
                            Model = "320d",
                            PurchaseDate = new DateTime(2019, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 27900m,
                            UserId = 2,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tesla",
                            CurrentMilage = 43100,
                            EngineVolume = 0.0,
                            FuelType = 2,
                            Model = "Model 3",
                            PurchaseDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 43990m,
                            UserId = 3,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.CarTire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TireId");

                    b.ToTable("CarTires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            InstalledDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TireId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            InstalledDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TireId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            InstalledDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TireId = 3
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 18m,
                            CarId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hand wash and interior cleaning"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 7.5m,
                            CarId = 2,
                            CategoryId = 2,
                            Date = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Winter windshield washer fluid"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 62m,
                            CarId = 3,
                            CategoryId = 3,
                            Date = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly garage parking pass"
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car washing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wiper fluid refill"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Parking and tolls"
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.FuelExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FuelExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kilometars")
                        .HasColumnType("int");

                    b.Property<decimal>("Liters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerLiter")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("FuelExpenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            FuelExpenseDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kilometars = 68940,
                            Liters = 42.50m,
                            PricePerLiter = 1.63m
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            FuelExpenseDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kilometars = 113020,
                            Liters = 55.10m,
                            PricePerLiter = 1.58m
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            FuelExpenseDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kilometars = 43580,
                            Liters = 0m,
                            PricePerLiter = 0m
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Company = "Allianz",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsuranceType = "Comprehensive",
                            Price = 640m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Company = "Generali",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsuranceType = "Comprehensive",
                            Price = 760m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Company = "Wiener Osiguranje",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsuranceType = "Comprehensive",
                            Price = 890m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("ServiceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Cost = 180m,
                            Description = "Oil and filter change",
                            Mileage = 69210,
                            ServiceDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceType = "Regular maintenance"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Cost = 320m,
                            Description = "Front brake pads replacement",
                            Mileage = 113450,
                            ServiceDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceType = "Brake service"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Cost = 95m,
                            Description = "High-voltage system diagnostic",
                            Mileage = 43820,
                            ServiceDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceType = "Battery check"
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Tire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Michelin",
                            Model = "Pilot Sport 5",
                            Price = 145m,
                            Season = "Summer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Continental",
                            Model = "PremiumContact 6",
                            Price = 138m,
                            Season = "Summer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Bridgestone",
                            Model = "Blizzak LM005",
                            Price = 152m,
                            Season = "Winter"
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marko.pavic@example.com",
                            Password = "Pass123!",
                            Username = "marko92"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivana.horvat@example.com",
                            Password = "Pass123!",
                            Username = "ivana87"
                        },
                        new
                        {
                            Id = 3,
                            Email = "petra.kovac@example.com",
                            Password = "Pass123!",
                            Username = "petra95"
                        });
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Car", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.CarTire", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.Car", "Car")
                        .WithMany("CarTires")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarExpenses.Model.Models.Tire", "Tire")
                        .WithMany("CarTires")
                        .HasForeignKey("TireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Tire");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Expense", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.Car", null)
                        .WithMany("Expenses")
                        .HasForeignKey("CarId");

                    b.HasOne("CarExpenses.Model.Models.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.FuelExpense", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.Car", "Car")
                        .WithMany("FuelExpenses")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Insurance", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.Car", "Car")
                        .WithMany("Insurances")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.ServiceRecord", b =>
                {
                    b.HasOne("CarExpenses.Model.Models.Car", "Car")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Car", b =>
                {
                    b.Navigation("CarTires");

                    b.Navigation("Expenses");

                    b.Navigation("FuelExpenses");

                    b.Navigation("Insurances");

                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.Tire", b =>
                {
                    b.Navigation("CarTires");
                });

            modelBuilder.Entity("CarExpenses.Model.Models.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
